id: P005511
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:39.804558
source_metadata:
  id: bdr:W1KG16156
  title: ཚད་མའི་སྐོར་གྱི་རྒྱ་གཞུང་རྩ་འགྲེལ།
  author: ''
  volumes:
    cecae0b5a6d74ff99fdaf9188aa3ae64:
      image_group_id: I1KG16172
      title: ''
      volume_number: 1
      total_pages: 532
      base_file: v001.txt
    13cfa18fad464f1aaeaccdbe1f4f2d3a:
      image_group_id: I1KG16173
      title: ''
      volume_number: 2
      total_pages: 402
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
