id: I48C95706
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:41:17+00:00'
last_modified: '2022-06-08T03:36:29.783397+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16156
  title: ཚད་མའི་སྐོར་གྱི་རྒྱ་གཞུང་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EE71:
      image_group_id: I1KG16172
      title: ''
      total_pages: 532
      order: 1
      base_file: EE71.txt
    7C5E:
      image_group_id: I1KG16173
      title: ''
      total_pages: 402
      order: 2
      base_file: 7C5E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
